// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_E3rc9dScmxBhevPZTKwPDSUdt7URZzw',
    appId: '1:356157817181:web:ec915c9ca34608f74628b4',
    messagingSenderId: '356157817181',
    projectId: 'focus-fa06b',
    authDomain: 'focus-fa06b.firebaseapp.com',
    storageBucket: 'focus-fa06b.firebasestorage.app',
    measurementId: 'G-PZPFRRC0CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNzKvdQFmoheRI8AaasBungK89LQaHIc',
    appId: '1:356157817181:android:df2bc85650da6da54628b4',
    messagingSenderId: '356157817181',
    projectId: 'focus-fa06b',
    storageBucket: 'focus-fa06b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUMD5uultb3dFA2GhCf3g7ns05OxmD8Q',
    appId: '1:356157817181:ios:03cfe706034722714628b4',
    messagingSenderId: '356157817181',
    projectId: 'focus-fa06b',
    storageBucket: 'focus-fa06b.firebasestorage.app',
    iosBundleId: 'com.example.focus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUMD5uultb3dFA2GhCf3g7ns05OxmD8Q',
    appId: '1:356157817181:ios:03cfe706034722714628b4',
    messagingSenderId: '356157817181',
    projectId: 'focus-fa06b',
    storageBucket: 'focus-fa06b.firebasestorage.app',
    iosBundleId: 'com.example.focus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_E3rc9dScmxBhevPZTKwPDSUdt7URZzw',
    appId: '1:356157817181:web:f32217ca8eb6bc8b4628b4',
    messagingSenderId: '356157817181',
    projectId: 'focus-fa06b',
    authDomain: 'focus-fa06b.firebaseapp.com',
    storageBucket: 'focus-fa06b.firebasestorage.app',
    measurementId: 'G-V182K8XHEQ',
  );
}
